# Generated by Django 3.1.2 on 2020-10-13 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plataforma', '0002_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ayudantia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.IntegerField(default=2)),
                ('horario', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('requisito', models.CharField(max_length=50)),
                ('puestos', models.IntegerField(default=1)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('hora', models.TimeField(auto_now=True)),
                ('estado', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.usuario')),
                ('ayudantia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postulaciones.ayudantia')),
            ],
        ),
    ]
