# Generated by Django 3.1.2 on 2020-10-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='codigo',
            field=models.IntegerField(default=0),
        ),
    ]
