# Generated by Django 3.1.2 on 2020-10-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_auto_20201014_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='codigo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
