# Generated by Django 3.1.3 on 2020-11-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_auto_20201014_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='intereses',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='curso',
            name='codigo',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
