# Generated by Django 3.1.3 on 2020-11-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0006_auto_20201105_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='intereses',
            field=models.TextField(),
        ),
    ]
