# Generated by Django 3.1.3 on 2020-11-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0007_auto_20201105_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='semestre',
            field=models.IntegerField(choices=[(0, 'Primer semestre'), (1, 'Segundo'), (2, 'Tercer'), (3, 'Cuarto'), (4, 'Quinto'), (5, 'Sexto'), (6, 'Septimo'), (7, 'Octavo'), (8, 'Noveno'), (9, 'Decimo'), (10, 'Onceavo'), (11, 'Doceavo o superior')], default=0),
        ),
    ]
