# Generated by Django 3.1.3 on 2020-11-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0008_usuario_semestre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='semestre',
        ),
        migrations.AddField(
            model_name='usuario',
            name='etapa_carrera',
            field=models.IntegerField(choices=[(0, 'Primer año'), (1, 'Segundo año'), (2, 'Tercer año'), (3, 'Cuarto año'), (4, 'Quinto año'), (5, 'Sexto año o superior')], default=0),
        ),
    ]
