# Generated by Django 3.1.2 on 2020-11-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0010_usuario_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='area',
            field=models.CharField(choices=[('0', 'Pregrado'), ('1', 'Postgrado'), ('2', 'Externo')], default=0, max_length=20),
        ),
    ]
