# Generated by Django 3.1.4 on 2020-12-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0011_auto_20201110_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='matricula',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='area',
            field=models.CharField(choices=[('Pregrado', 'Pregrado'), ('Postgrado', 'Postgrado'), ('Externo', 'Externo')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='etapa_carrera',
            field=models.IntegerField(choices=[(1, 'Primer año'), (2, 'Segundo año'), (3, 'Tercer año'), (4, 'Cuarto año'), (5, 'Quinto año'), (6, 'Sexto año o superior')], default=0),
        ),
    ]
