# Generated by Django 3.1.4 on 2020-12-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0014_auto_20201212_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='area',
            field=models.CharField(choices=[('Docente', 'Docente'), ('Pregrado', 'Pregrado'), ('Postgrado', 'Postgrado'), ('Externo', 'Externo')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='etapa_carrera',
            field=models.IntegerField(choices=[(0, 'No aplica'), (1, 'Primer año'), (2, 'Segundo año'), (3, 'Tercer año'), (4, 'Cuarto año'), (5, 'Quinto año'), (6, 'Sexto año o superior')], default=0),
        ),
    ]
