# Generated by Django 3.1.5 on 2021-01-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0015_auto_20201212_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='area',
            field=models.CharField(choices=[('No aplica', 'No aplica'), ('Pregrado', 'Pregrado'), ('Postgrado', 'Postgrado'), ('Externo', 'Externo')], default=0, max_length=20),
        ),
    ]
