# Generated by Django 3.1.4 on 2021-01-13 17:01

import apps.plataforma.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0016_auto_20210104_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='registro_notas',
            field=models.FileField(blank=True, null=True, upload_to=apps.plataforma.models.user_path),
        ),
    ]
